# -*- coding: utf-8 -*-
"""Python6_for-loops1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Am6mrvHM-lm3TqiNszk-q4PAXs1YJ9O
"""

# Loops are in built funtions in all programming language to perform an action iteractively (multiple times)
# There are two main types of loops - (1)for and (2)while
# Let us explore the for loop

# This will print same statement ten times
for i in range(10):
  print("I am sorry, I will not repeat it again")

####### NOTE: always remember to add 1 to the final range because python does zero (0) indexing.... #########

# Generating a table of a number series from 1 to 10
for i in range(1,11):
  print(i)

# Generating a table of any number to any given multiple
number=int(input("Submit the number whose table you wish to generate "))

times=int(input("The limit to which you want to generate the number "))

for i in range (1, times+1):
  table=number*i
  print(number, "*", i, "=", table)

# Generating all odd numbers from 1 to 10
for x in range(1,11):
  if x%2!=0 :
    print (x)

# Generating all even numbers from 1 to 10
for x in range (1,11):
  if x%2==0 :
    print (x)