# -*- coding: utf-8 -*-
"""Python1_introduction-to-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vgPyvRA21RMISvV34hO75qQ-gh-2qfPz

**INTRODUCTION TO PYTHON**
"""

print("Introduction to python")

# Using python as a simple calculator

2+5

2*5*10

2**4

6%4

2*(3+7)/5

name=input("Input your first name: ")

print("My name is ", name)