# -*- coding: utf-8 -*-
"""Python7_for-loop_strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OCmynKcUiRRLx37RoEJeLjAgLcBnW2e1
"""

# Loop to generate a number series
for i in range(1,11):
  print(i)

# for loop on string
dna = "GAATTC"
for i in dna:
  print(i)

# for loop on string with conditional print
dna = "AATTGGCC"
for i in dna :
  #checking for purines and pyrimidines
  if i=="G" or i=="A":
    print(i, "Purine")
  else :
    print(i, "Pyrimidine")

# counting in loop
purine=0; pyrimidine=0
# NOTE: single equality sign is for assignment of 0 value while double equality sign is used to check for equality
dna="GAATTCAAAA"
# loop start
for i in dna :
  if i=="G" or i=="A":
    #if i=="A" :
    print(i, "Purine")
    purine+=1
  else:
    print(i, "Pyrimidine")
    pyrimidine+=1
# loop end
print("Total purines = ",purine, "Total pyrimidine = ", pyrimidine)

# Declaring a list
list1 = ["DNA", "RNA", "Proteins"]

# for loop on list
for i in list1:
  print(i)

# Printing corresponding elements for 2 lists
list2 = ["Replication", "Transcription", "Translation"]

for i in range(3) :
  print(i, list1[i], "-", list2[i])

central_dogma=[]
molecule=["DNA","RNA","Proteins"]
process=["Replication", "Transcription", "Translation"]

for i in range(3):
  central_dogma.append(molecule[i])
  central_dogma.append(process[i])
  print(i, central_dogma)

print("\n", central_dogma)