# -*- coding: utf-8 -*-
"""Python_5_DNA _composition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8_cDGy6osG1KOTbL9b25zGf9Kbtv25j

# **Lets take input from user, then check the composition of DNA sequence and also calculate the GC content**
"""

# Taking DNA sequence as input
dna=input("Enter a DNA sequece: ")

# Calculating length of input DNA sequence
length=len(dna)
print(length)

# Converting to lower case
dna=dna.lower()
print(dna)

# Converting back to upper case
dna=dna.upper()
print(dna)

# Counting A, T, G, C
g=dna.count('G')
c=dna.count('C')
a=dna.count('A')
t=dna.count('T')
n=dna.count('N')

# Printing the results. 
# NOTE "\n" is used to direct python to print the subsequent objects down.
print(
    "Length=",length,"\n",
    "N=", n,
    "G=", g,
    "C=", c,
    "A=", a,
    "T=", t
)

# Calculating the G+C % in the sequence
gc=((g+c)/length)*100.0
print("GC content = ",gc, "%")

# Application of this procedure: calculating the primer meltig temperature, as in the following,
tm=(4*(g+c)+2*(a+t))
print("The melting temperature of the oligo is ", tm)

# Converting to RNA
rna=dna.replace("T","U")
print("RNA Sequence ",rna)

# Find the first occurence of AUG (start codon) -substring in a string
start=rna.find("AUG")
print(start+1)
# Addition of +1 is because python starts counting from 0 (zero indexing), so we need to make it correspond to the exact number

# Find the first occurence of AUG from the reverse or 3' end
start2 = rna.rfind("AUG")
print(start2+1)
# Addition of +1 is because python starts counting from 0 (zero indexing), so we need to make it correspond to the exact number

# Starts searching for pattern from x poition onwards
start3 = rna.find("AUG",20)
print(start3+1)
# Addition of +1 is because python starts counting from 0 (zero indexing), so we need to make it correspond to the exact number