# -*- coding: utf-8 -*-
"""Python2_datatypes.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jsmyQ--kh2BaQgS0fQc0_ERmQfnLbyTE

Today we have a look at **numeric and string data types** in Python.
The numeric data type itself can be an **integer, float or complex**
anything within double quotes is a **string** - single alphabet, a combination of alphabets, a combination of alphabets and numbers, alphabets and special characters
"""


# Assigning variables
DNA = "ATTGCC"

num1 = 123

num2 = 21.19

num3 = -15

num4 = 2 + 4j


#How to check data types:

print("The data type of DNA is ", type(DNA))

print("The data type of num1 is ", type(num1))

print("The data type of num2 is ", type(num2))

print("The data type of num3 is ", type(num3))

print ("The data type of num4 is ", type(num4))

num4 = "2"

print ("The data type of num4 is ", type(num4))


# Notice the concatenation that follows:

number1 = input("Input the first number ")

number2 = input("Input the second number ")

sum1 = number1 + number2

print(sum1)

"""So you know that there is a problem here. 2+5 cannot be 25. Why is this happening? This happens because any input taken from the terminal is by default treated as a string and when plus is used between 2 strings, it concatenates the strings together. 

**Can we still get the sum right?**
"""


# Let us avoid concatenation by defining the nature of the data types we use:

print (type(number1))

sum = int(number1) + int(number2)

print(sum)

num6=int(input("Input a number "))

print (type(num6))


# How to check if our predicted datatype is the real datatype

isinstance(num6, int)

isinstance(num6, str)

print(DNA)


# Let's now understand the string function of slicing where we can pull out any character or list of characters from a string:

print(DNA[0])

print(DNA[0:4])
