# -*- coding: utf-8 -*-
"""Python3_string_functions.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gM75Dy3seyq9jTbADTxHH_ouKcy8uyaT

**STRING OPERATION.**
"""

a = "Titanic"

print(type(a))

isinstance(a,str)

# Length of string

length = len(a); print(length)

# Converting uppercase/lowercase

uc = a.upper(); print(uc)

lc = a.lower(); print(lc)

title = lc.title()
print(title)

"""**A sentence as a string**"""

sentence = "All that remains is what remains"

print(len(sentence))

isinstance(sentence,int)

print(type(sentence))

print (sentence.count('remains'))

print (sentence.count('a'))

print (sentence.count('a', 10))

print (sentence.find("remains"))

print (sentence.rfind('remains'))

print (sentence.find("saw"))

print (sentence.rstrip("ains"))

remains = sentence.rstrip('ains')
print (remains)

dna = "AATTGGCCAA"
print (len(dna))

print (dna.count("A"))

print (dna.find("A"))

print (dna.rfind('A'))

print (dna)

print ("dna[0] : ", dna[0])

print ("dna[0:5] : ", dna[0:5])

print ("dna[0:8] : ", dna[0:8])

print ("dna [2:4] :", dna [2:5])

dna2 = "AAAA"
dna3 = dna + dna2
dna4 = dna2 + dna
print ('dna3 : ', dna3)
print ('dna4 : ', dna4)

dna5 = dna2*5
print (dna5)
print (len(dna5))